server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-svc.healthcare.svc.cluster.local:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/doctors/ {
        proxy_pass http://doctor-svc.healthcare.svc.cluster.local:3002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/patients/ {
        proxy_pass http://patient-svc.healthcare.svc.cluster.local:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/appointments/ {
        proxy_pass http://appointment-svc.healthcare.svc.cluster.local:3004;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/pharmacy/ {
        proxy_pass http://pharmacy-svc.healthcare.svc.cluster.local:3005;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/labs/ {
        proxy_pass http://lab-svc.healthcare.svc.cluster.local:3006;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        access_log off;
        return 200 '{"status":"healthy","service":"frontend"}';
        add_header Content-Type application/json;
    }
}