apiVersion: v1
kind: Service
metadata:
  name: service-for-monosamedb
  labels:
    app: service-for-monosamedb

spec:
  type: NodePort
  selector:
    app: spring-boot-k8s-samedb

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
