apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: monolith-app
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_THYMELEAF_CACHE: "false"
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "demo2"
  # Note: DB URL set via env var in Deployment, using mysql-service
