apiVersion: v1
kind: Service
metadata:
  name: monolith-app-service
  labels:
    app: monolith-app
spec:
  type: NodePort
  selector:
    app: monolith-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
