apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: monolith-app
type: Opaque
stringData:
  mysql-root-password: root  # password (root init)
  mysql-user: root  # myuser
  mysql-password: root  # mypassword
  mysql-database: userdb  # userdb
